version: '3.8'

services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /p:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /data/docker/:/var/lib/docker:ro
    command:
      - '--housekeeping_interval=10s'
      - '-allow_dynamic_housekeeping=false'
      - '--docker_only=true'
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:8.3.3
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_prom_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/ # https://grafana.com/grafana/dashboards/1860
      
volumes:
  grafana_prom_data: {}
  prometheus_data: {}
